// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvUmr7WXitMGweH1w4525V4IEFTp38Wes',
    appId: '1:11133951879:android:47ce9e8d1e75b701df3d22',
    messagingSenderId: '11133951879',
    projectId: 'taskmate-9ffed',
    storageBucket: 'taskmate-9ffed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYCIMHgGJ4GyEnI_ZwE1bSA1VK2ljTUR0',
    appId: '1:11133951879:ios:8309dcd6267b47addf3d22',
    messagingSenderId: '11133951879',
    projectId: 'taskmate-9ffed',
    storageBucket: 'taskmate-9ffed.firebasestorage.app',
    iosBundleId: 'com.example.flutterProjects',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQtEjqDJl1GPnmIx7aumSs2XnbUT_-3to',
    appId: '1:11133951879:web:eb3b245051f058cedf3d22',
    messagingSenderId: '11133951879',
    projectId: 'taskmate-9ffed',
    authDomain: 'taskmate-9ffed.firebaseapp.com',
    storageBucket: 'taskmate-9ffed.firebasestorage.app',
    measurementId: 'G-GJW4S12TNV',
  );
}
